TCD/JDJ/RULE19-32
pnnl/ruleset-checking-tool pull request #1092
Opened 2023-05-05 16:47 UTC by JacksonJ-KC

2023-05-07 16:50 UTC, yunjoonjung-PNNL approved these changes

2023-05-07 16:50 UTC, yunjoonjung-PNNL commented on rct229/ruletest_engine/ruletest_jsons/ashrae9012019/section19/rule_19_32.json
> +                                                        "lighting_space_type": "COMPUTER_ROOM"
Could you add the ```floor_area``` key here?

2023-05-07 16:51 UTC, yunjoonjung-PNNL requested changes

2023-05-07 16:51 UTC, yunjoonjung-PNNL commented on rct229/ruletest_engine/ruletest_jsons/ashrae9012019/section19/rule_19_32.json
> +                                                        "lighting_space_type": "COMPUTER_ROOM"
Could you add the ```floor_area``` key here?

2023-05-08 16:58 UTC, JacksonJ-KC commented on rct229/ruletest_engine/ruletest_jsons/ashrae9012019/section19/rule_19_32.json
> +                                                        "lighting_space_type": "COMPUTER_ROOM"
Added

2023-05-08 17:16 UTC, yunjoonjung-PNNL approved these changes
Looks great to me! Thank you.

2023-05-08 17:16 UTC, yunjoonjung-PNNL approved these changes
Looks great to me! Thank you.

2023-05-12 17:11 UTC, merged