RS/YJ/Rule 11-6
pnnl/ruleset-checking-tool pull request #1523
Opened 2024-09-12 18:39 UTC by yunjoonjung-PNNL

This rule hasn't been tested as the required function wasn't merged. I'll remove the draft mark when I finished the testing. Thanks!

2024-09-17 18:17 UTC, yunjoonjung-PNNL commented
I'm a bit confused by the RDS logic, but my interpretation of it is as follows:
1. if the '``are_thermal_losses_modeled``' key doesn't exist => pass
2. if the '``are_thermal_losses_modeled``' is False => pass
3. if the '``are_thermal_losses_modeled``' is True => fail

Please let me know if my interpretation is wrong. Thank you!

2024-10-04 15:34 UTC, weilixu reviewed
In general, I feel the evaluation shall be at service water heating system distribution level. The implmenetation currently is in the buildilng level.

2024-10-04 15:34 UTC, weilixu commented on rct229/rulesets/ashrae9012019/section11/section11rule6.py
> +        class BuildingSegmentRule(RuleDefinitionBase):
My take is this rule should be at `service_water_heating_distribution_systems` level, not building level. (See RDS Evaluation Context)

In RMD Rule, we need to add an `is_applicable` to check if there are `service_water_heating_distribution_systems` or not.
In RMD Rule `create_data`, we should call `get_swh_components_associated_with_each_swh_distribution_system` to get the data.

In the ServiceWaterHeatingDistributionSystem, we need to check every piping, including children, is modeled with thermal losses turned to false.
You can reuse the same code block searches for piping under a ServiceWaterHeatingDistributionSystem from the `get_swh_components_associated_with_each_swh_distribution_system` function.

2024-10-04 15:36 UTC, weilixu requested changes

2024-10-04 15:36 UTC, weilixu commented on rct229/rulesets/ashrae9012019/section11/section11rule6.py
> +            )
Need a `is_applicable` here.

2024-10-14 21:56 UTC, yunjoonjung-PNNL commented
This PR will be replaced with a new 11-6 PR.

2024-10-14 21:56 UTC, closed without merging