Create Rule21-19.md
pnnl/ruleset-checking-tool pull request #238
Opened 2022-02-06 11:10 UTC by xingcx

2022-02-08 00:26 UTC, mkarpman approved these changes

2022-02-15 20:37 UTC, supriyagoel commented on docs/section21/Rule21-19.md
> +
@mkarpman do we need to convert the minimum eff in a specific metric to other metrics and verify the value? For example, E+ only takes in Et, the RMR is likely to include Et on all 3 cases. 
The challenge with this is using standard conversion methodology, one option would be to follow the PRM RM and document the same out here.

2022-02-15 20:37 UTC, supriyagoel requested changes
question on supporting other metrics for eff

2022-02-22 22:35 UTC, supriyagoel commented on docs/section21/Rule21-19.md
> +
as discussed on the RDS call, 
![image](https://user-images.githubusercontent.com/8323384/155231081-432282ef-dee3-44ed-9938-ed7ce5871d78.png)

2022-03-09 06:42 UTC, supriyagoel approved these changes

2022-03-10 16:36 UTC, merged