Update Rule12-5.md
pnnl/ruleset-checking-tool pull request #26
Opened 2021-04-19 04:23 UTC by xingcx

2021-05-04 14:57 UTC, JasonGlazer commented
Original discussion at the link below. Please give this link time to load. This page might take a few seconds to load and another 4-8 seconds to land at the correct comment:

https://github.com/pnnl/ruleset-checking-tool/pull/19#discussion_r614289436

2021-12-06 20:49 UTC, supriyagoel commented on docs/section12/Rule12-5.md
> +
we should now use ID for matching.

2021-12-06 20:52 UTC, supriyagoel requested changes

2021-12-06 20:52 UTC, supriyagoel commented on docs/section12/Rule12-5.md
> +
@xingcx should remove thermal block.

2021-12-07 05:52 UTC, xingcx commented on docs/section12/Rule12-5.md
> +
Updated.

2021-12-07 05:52 UTC, xingcx commented on docs/section12/Rule12-5.md
> +
Updated.

2021-12-15 00:17 UTC, mcneillj commented
Archived. No longer needed.

2021-12-15 00:17 UTC, closed without merging