Update Rule12-4.md
pnnl/ruleset-checking-tool pull request #33
Opened 2021-04-26 03:36 UTC by xingcx

2021-05-04 14:52 UTC, JasonGlazer commented
Original discussion at the link below. Please give this link time to load. This page might take a few seconds to load and another 4-8 seconds to land at the correct comment:

https://github.com/pnnl/ruleset-checking-tool/pull/19#discussion_r613525487

2021-12-06 20:51 UTC, supriyagoel requested changes

2021-12-06 20:51 UTC, supriyagoel commented on docs/section12/Rule12-4.md
> +  - For each thermal_block in building segment: ```thermal_block_baseline in building_segment_baseline.thermal_blocks:```
@xingcx should remove thermal block

2021-12-06 20:51 UTC, supriyagoel commented on docs/section12/Rule12-4.md
> +    - Get the name of the space: ```space_name_baseline = space_baseline.name```
@xingcx should reference using ID instead of name now.

2021-12-07 05:40 UTC, xingcx commented on docs/section12/Rule12-4.md
> +  - For each thermal_block in building segment: ```thermal_block_baseline in building_segment_baseline.thermal_blocks:```
Updated.

2021-12-15 00:17 UTC, mcneillj commented
Archived. No longer needed.

2021-12-15 00:17 UTC, closed without merging