Create Rule22-26.md
pnnl/ruleset-checking-tool pull request #345
Opened 2022-03-07 13:50 UTC by xingcx

resolves #[307]

2022-03-08 20:15 UTC, mkarpman approved these changes

2022-03-09 07:06 UTC, supriyagoel requested changes

2022-03-09 07:06 UTC, supriyagoel commented on docs/section22/Rule22-26.md
> +  - Check if primary and secondary loops are modeled correctly, continue to rule logic: `if primary_secondary_loop_dictionary["PRIMARY"] AND primary_secondary_loop_dictionary["SECONDARY"]: CHECK_RULE
as discussed today, 'Check if primary and secondary loops are modeled correctly' should become 'Check if primary and secondary loops  are modeled'

2022-03-09 07:06 UTC, supriyagoel commented on docs/section22/Rule22-26.md
> +
pump power per fflow rate is in W/s-L, this will have to be converted to W/GPM. there should be a note here to convert W/s-l to W/gpm

2022-04-26 05:00 UTC, supriyagoel approved these changes

2022-05-04 01:40 UTC, merged