Create Rule22-27.md
pnnl/ruleset-checking-tool pull request #346
Opened 2022-03-07 13:52 UTC by xingcx

resolves #308

2022-03-08 20:17 UTC, mkarpman approved these changes

2022-03-09 07:07 UTC, supriyagoel requested changes

2022-03-09 07:07 UTC, supriyagoel commented on docs/section22/Rule22-27.md
> +  - Check if primary and secondary loops are modeled correctly, continue to rule logic: `if primary_secondary_loop_dictionary["PRIMARY"] AND primary_secondary_loop_dictionary["SECONDARY"]: CHECK_RULE
same commnet as 22-26, should say 'modeled' instead of 'modeled correctly'

2022-03-09 07:07 UTC, supriyagoel commented on docs/section22/Rule22-27.md
> +
add note for unit conversion from W/s-l to W/gpm

2022-04-26 04:58 UTC, supriyagoel approved these changes

2022-05-04 01:30 UTC, merged