Rs/yj/rule5 11
pnnl/ruleset-checking-tool pull request #404
Opened 2022-04-01 03:01 UTC by yunjoonjung-PNNL

I would appreciate it if you reviewed this pull request.

2022-04-01 12:02 UTC, weilixu requested changes

2022-04-01 12:02 UTC, weilixu commented on rct229/rules/section5/section5rule11.py
> +                    and target_u_factor_res != target_u_factor_nonres
Here, it seems we do not need the None check?
We are checking if `target_u_factor_res != target_u_factor_nonres` regardless of whether they are none or values.

2022-04-01 18:35 UTC, yunjoonjung-PNNL commented
I updated the code based on the comments and would appreciate it if this branch could be reviewed again.

2022-04-01 19:52 UTC, weilixu approved these changes

2022-04-03 23:49 UTC, charliepnnl approved these changes
Approved with two comments that should be addressed.

2022-04-04 20:36 UTC, merged