Update Rule5-3.md
pnnl/ruleset-checking-tool pull request #46
Opened 2021-05-10 05:54 UTC by xingcx

2021-05-12 15:10 UTC, JasonGlazer requested changes

2021-05-12 15:10 UTC, JasonGlazer commented on docs/section5/Rule5-3.md
> +    **Rule Assertion:** Baseline above-grade wall construction modeled matches Table G3.4-1 to G3.4-8: ```surface_performance_value_baseline == surface_performance_target```
This seems to be verifying the c-factor which is good. But it is also supposed to be verifying that the layer by layer description (if provided) conforms to Normative Appendix A for below grade walls. So it should match "8 in. medium weight concrete block with density of 115 lb/ft3 and solid grouted cores."

2021-05-12 15:10 UTC, JasonGlazer commented on docs/section5/Rule5-3.md
> +      - Get baseline contruction from Table G3.4-1 to G3.4-8 based on climate zone, space conditioning type and function type: ```surface_performance_target = data_lookup(table_G3_4,climate_zone,spac
adding the reference to the table is good, make sure it is done on the other "data_lookups"

2021-07-27 06:01 UTC, supriyagoel approved these changes

2021-07-27 21:45 UTC, mkarpman approved these changes

2021-08-02 12:10 UTC, JasonGlazer approved these changes

2021-08-02 19:26 UTC, merged