Ruletest JSON 6-2
pnnl/ruleset-checking-tool pull request #488
Opened 2022-06-23 18:38 UTC by jugonzal07

Added ruletest 6-2 from updated lighting master spreadsheet

2022-06-28 20:04 UTC, weilixu requested changes

2022-06-28 20:04 UTC, weilixu commented on rct229/ruletest_engine/ruletest_jsons/section6/rule_6_2.json
> +                                                            },
For failed cases, we will need the sum of spaces power per area greater than 11.8 W/m2

2022-06-28 20:08 UTC, weilixu requested changes

2022-07-01 22:52 UTC, yunjoonjung-PNNL approved these changes

2022-07-01 22:52 UTC, yunjoonjung-PNNL commented on rct229/ruletest_engine/ruletest_jsons/section6/rule_6_2.json
> +            "rule_description": "Interior lighting power for spaces in proposed building with hardwired lighting, including hotel/motel guest rooms and dormitory living quarters shall be >= the value
This part is slightly different from the RDS. Could you check this out?

2022-07-18 16:52 UTC, weilixu approved these changes

2022-07-18 16:52 UTC, merged