RS+RT/YJ/RULE22-30
pnnl/ruleset-checking-tool pull request #727
Opened 2022-10-20 18:43 UTC by yunjoonjung-PNNL

I'd appreciate it if you reviewed this PR.

2022-10-21 03:14 UTC, charliepnnl requested changes
My comments for this rule are essentially the same as for Rule22-29.

2022-10-24 01:39 UTC, weilixu commented
> My comments for this rule are essentially the same as for Rule22-29.

I second - these two are quite similar

2022-10-31 22:21 UTC, yunjoonjung-PNNL commented
I added ```CondensingFluidLoopRule``` instead of ```ChillerRule``` because rule check is performed at the condensing ```fluid_loops``` level rather than chiller level.

2022-11-03 01:17 UTC, weilixu approved these changes

2022-11-03 01:21 UTC, merged