Section 15 rule tests to 0.23
pnnl/ruleset-checking-tool pull request #824
Opened 2022-12-06 02:11 UTC by jugonzal07

Updated transformer rule test JSONs to latest schema

2022-12-06 07:11 UTC, yunjoonjung-PNNL approved these changes
Looks great to me. Similar to section 12, I'd appreciate it if you could check whether we need 15-7 and 8 RMDs.

2022-12-06 18:47 UTC, weilixu requested changes

2022-12-06 18:47 UTC, weilixu commented on rct229/ruletest_engine/ruletest_jsons/section15/rule_15_5.json
> +                                "efficiency": 0.98
It seems the rquired baseline transformer efficiency is 0.989

2022-12-06 18:47 UTC, weilixu commented on rct229/ruletest_engine/ruletest_jsons/section15/rule_15_5.json
> +                                "efficiency": 0.99
The efficiency needs to be higher than 0.9928 for THREE_PHASE transformer with 30000 capacity. Otherwise 15-5 will fail the applicability check

2022-12-06 18:47 UTC, weilixu commented on rct229/ruletest_engine/ruletest_jsons/section15/rule_15_6.json
> +                                "efficiency": 0.98
This needs to be higher than 0.989

2022-12-06 18:47 UTC, weilixu commented on rct229/ruletest_engine/ruletest_jsons/section15/rule_15_6.json
> +                                "efficiency": 0.983
This needs to be higher than 0.9928

2022-12-06 18:47 UTC, weilixu commented on rct229/ruletest_engine/ruletest_jsons/section15/rule_15_5.json
> +                                "efficiency": 0.99
The efficiency needs to be higher than 0.9928 for THREE_PHASE transformer with 30000 capacity. Otherwise 15-5 will fail the applicability check

2022-12-07 14:50 UTC, jugonzal07 commented
It appears 15-c still fails and perhaps we should get rid of 15-7 and 15-8? Let me know if you'd like me to look into that.

2022-12-08 15:08 UTC, jugonzal07 commented
done! Also, sorry I pushed a commit before finishing the message. Commit [e09edb1](https://github.com/pnnl/ruleset-checking-tool/pull/824/commits/e09edb1e445773fdbfcf4dc017c6457fbd72cbc5) should read "Removed 15-7 and 15-8 ruletest JSONs"

2022-12-11 17:52 UTC, merged