Rds/kjw/rule 23 3
pnnl/ruleset-checking-tool pull request #879
Opened 2023-01-01 11:57 UTC by KarenWGard

some efficiency updates and typos fixed

2025-02-05 15:58 UTC, KarenWGard commented on docs/section23/Rule23-3.md
> +          - multiply each value in the hourly schedule by the minimum airflow rate, and append this to the list of minimum volume flowrates: `minimum_volume_list_p.append([i * min_volume_p for i in o
There is a case where there are two systems in a proposed zone that operates at different times - ie, they each separately meet the minimum.

2025-02-05 16:31 UTC, claperle commented on docs/section23/Rule23-3.md
> +        - Case 2: Else, if the minimum volume setpoint is equal to the maximum of 30% of peak primary design airflow, the rate required for minimum outside air, then UNDETERMINED with a note.  Due to
I think this hsould be if terminal_b.minimum_airflow == terminal_b.primary_airflow * 0.3: UNDETERMINED

2025-02-05 16:35 UTC, KarenWGard commented on docs/section23/Rule23-3.md
> +        - find the maximum value in the list: `min_volume_p = max(min_volume_flow_tot_p)`
no, because the list contains the minimum volume flowrate for each hour.  The assumption is that there may be some hours where equipment is scheduled off.  If there is only one piece of equipment in the zone, then the list would contain only zeros and whatever the normal minimum volume flow is, so the maximum of these two values would be the minimum volume flowrate (we can discuss on the call if you like)

2025-02-05 16:36 UTC, claperle commented on docs/section23/Rule23-3.md
> +        - Case 1: For each terminal that is served by HVAC system that is Type-5, 7, 7a, 5b, 7b, 7c, 6, 8, 8a, 6b, 8b, if minimum volume setpoint is equal to the maximum of: 30% of peak primary desig
This is because we do not know for sure that the minimum_volume_p is what is required by codes and standards so we don't want to pass it just because it equals that.

2025-02-05 16:37 UTC, claperle commented on docs/section23/Rule23-3.md
> +        - find the maximum value in the list: `min_volume_p = max(min_volume_flow_tot_p)`
Let's discuss. If one piece of equipment operated and the other was not then that would be the minmum flowrate.

2025-02-05 16:39 UTC, KarenWGard commented on docs/section23/Rule23-3.md
> +        - Case 2: Else, if the minimum volume setpoint is equal to the maximum of 30% of peak primary design airflow, the rate required for minimum outside air, then UNDETERMINED with a note.  Due to
Case 1 has three conditions - the ones related to the baseline system, and the one related to the proposed.  In case 2, we're looking to see if `terminal_b.minimum_airflow` is equal to one of the cases related to the baseline system, but greater than the `minimum_volume_p`.  We don't need to do the `if terminal_b.minimum_airflow > minimum_volume_p` check here because it's already covered by the case 1 check, which evaluted to false.

2025-02-05 16:41 UTC, KarenWGard commented on docs/section23/Rule23-3.md
> +        - find the maximum value in the list: `min_volume_p = max(min_volume_flow_tot_p)`
ok, I see your logic.  I think you're right.

2025-02-05 16:42 UTC, KarenWGard commented on docs/section23/Rule23-3.md
> +        - Case 1: For each terminal that is served by HVAC system that is Type-5, 7, 7a, 5b, 7b, 7c, 6, 8, 8a, 6b, 8b, if minimum volume setpoint is equal to the maximum of: 30% of peak primary desig
using proposed minimum volume flowrate is what we discussed on the call last week & how we are getting to a solid pass, not Pass-if to keep this a mandatory rule.

2025-02-05 16:45 UTC, claperle commented on docs/section23/Rule23-3.md
> +        - Case 1: For each terminal that is served by HVAC system that is Type-5, 7, 7a, 5b, 7b, 7c, 6, 8, 8a, 6b, 8b, if minimum volume setpoint is equal to the maximum of: 30% of peak primary desig
I think we have a miscommunication. Let's talk on the call. I am just saying i don't think we should pass it if terminal_b.minimum_airflow equals minimum_volume_p and is greater then terminal_b.primary_airflow * 0.3. Thhe way it is written now this would result in a pass. I think the terminal_b.primary_airflow * 0.3 condition needs to be met for us to allow a solid pass.

2025-02-05 20:19 UTC, KarenWGard commented on docs/section23/Rule23-3.md
> +        - Case 1: For each terminal that is served by HVAC system that is Type-5, 7, 7a, 5b, 7b, 7c, 6, 8, 8a, 6b, 8b, if minimum volume setpoint is equal to the maximum of: 30% of peak primary desig
re-write Case 1 to be:

`if terminal_b.minimum_airflow == MAX(terminal_b.primary_airflow * 0.3, terminal_b.minimum_outdoor_airflow) && terminal_b.minimum_airflow >= minimum_volume_p: PASS`

2025-04-24 15:34 UTC, claperle approved these changes

2025-06-11 16:17 UTC, yunjoonjung-PNNL commented on docs/section23/Rule23-3.md
> +        - Case 2: Else, if the minimum volume setpoint is equal to the maximum of 30% of peak primary design airflow, the rate required for minimum outside air, then UNDETERMINED with a note.  Due to
There are 2 typos in the message. ```airlfow``` should be ```airflow``` and ```accredidation``` should be ```accreditation```.

2025-06-11 16:18 UTC, yunjoonjung-PNNL commented on docs/section23/Rule23-3.md
> +        - find the minimum non-zero value in the list: `min_volume_p = min(filter(lambda x: x != 0, min_volume_flow_tot_p))`
```min_volume_p``` isn't used anywhere. Why would we need it?

2025-06-11 16:20 UTC, yunjoonjung-PNNL commented on docs/section23/Rule23-3.md
> +        - Case 1: For each terminal that is served by HVAC system that is Type-5, 7, 7a, 5b, 7b, 7c, 6, 8, 8a, 6b, 8b, if minimum volume setpoint is equal to the maximum of: 30% of peak primary desig
To be consistent, ```minimum_volume_p``` should be ```min_volume_p```.

2025-06-17 17:27 UTC, weilixu requested changes

2025-06-17 17:27 UTC, weilixu commented on docs/section23/Rule23-3.md
> +        - find the minimum non-zero value in the list: `min_volume_p = min(filter(lambda x: x != 0, min_volume_flow_tot_p))`
These two lines are calculating the minimum air volume for the HVAC system, not terminal. The assertion cases are not using HVAC system level data to confirm the calculation.

2025-06-17 17:27 UTC, weilixu commented on docs/section23/Rule23-3.md
> +        - find the minimum non-zero value in the list: `min_volume_p = min(filter(lambda x: x != 0, min_volume_flow_tot_p))`
@KarenWGard

2025-06-30 22:23 UTC, merged